[gcp_service_account]
type = "service_account"
project_id = "nice-dispatcher-481000-h9"
private_key_id = "..."
private_key = "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"
client_email = "streamlit-fiscalizacao@nice-dispatcher-481000-h9.iam.gserviceaccount.com"
client_id = "..."
auth_uri = "..."
token_uri = "..."
auth_provider_x509_cert_url = "..."
client_x509_cert_url = "..."
universe_domain = "googleapis.com"
# A URL deve ser uma chave ANINHADA aqui, pois é a opção que estamos testando
spreadsheet_url = "https://docs.google.com/spreadsheets/d/1b8HQ8fVlPN2QPjcRxBKwqu9tEyJCnDvYPzJsPjEMLuA/edit"

# Se houver outros blocos, mantenha-os se necessário, mas para o APP principal,
# a estrutura acima é o MÍNIMO necessário.
